### ISSUE TITLE
Cancelled Downloads Don't Clear

### ISSUE THREAD

**Issue by yungthud** [ArmandGrillet/Snap#2]
This extension works flawlessly, except for one issue I'm having: cancelled downloads don't automatically clear.

I used to use the extension 'Always Clear Downloads', which can automatically clear cancelled downloads, but that extension only clears after a 5-second delay (unlike Snap, it doesn't clear instantly).

Any ideas?

**Comment by armandgrillet** [comment]
This is a known bug but I don't plan to fix it.

Snap uses `chrome.downloads.onChanged` to erase the download exactly after the time wanted, contrary to Clear Downloads which is only using an interval. The problem is that this alarm only detects when a download is complete, not canceled, because `chrome.browsing`only offers [three states](https://developer.chrome.com/extensions/downloads#type-State) and there is not `canceled` thus I cannot detect and remove cancelled downloads with this API. 

I could use `chrome.browsingData`like Clear Downloads but I wouldn't be able to offer the exact timer that Snap uses now (when you're selecting a 2 seconds delay, the download will be removed after exactly 2 seconds) thus I won't update Snap, sorry.
